# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bh1O1p1LNZ5XKNxKPi-SW0DnxlzKxNre
"""

import random

# Função para ordenar a lista usando o algoritmo Insertion Sort
def insertion_sort(lista):
    for i in range(1, len(lista)):
        chave = lista[i]
        k = i
        while k > 0 and chave < lista[k - 1]:
            lista[k] = lista[k - 1]
            k -= 1
        lista[k] = chave

# Gerar a lista aleatória
lista = [random.randint(0, 100) for _ in range(10)]
print("Lista não ordenada:")
print(lista)

# Ordenar a lista usando o Insertion Sort
insertion_sort(lista)

print("Lista ordenada:")
print(lista)