# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sHV7dPlkKzOKb5GsZ7OJiqM7MhFzqp2B
"""

def insertionSort(list):

 for i in range(1, len(list)):
  aux = list[i]
  x = i - 1

  while x > 0 and aux < list[x - 1]:
      list[x]  = list[x-1]
      x = x -1

  list[x] = aux

list = [124, 111, 13, 50, 69, 43, 89, 66, 3, 1, 67, 100]
insertionSort(list)
for i in range(len(list)):
  print("% d" % list[i])